= Introduction <intro>

In every election, voters face the challenge of casting their ballots in a way that maximizes their influence on the outcome. Ideally, simply voting their preferences would do just that. However, in most practical cases there _is_ no strategy that is optimal regardless of how others vote (a dominant strategy), including honest voting. This is explained by the Gibbard–Satterthwaite theorem, which proves that any non-dictatorial voting rule with at least three alternatives has this property of having no dominant strategy. This landmark result shows that all reasonable voting methods are susceptible to exploitation, in the sense that voters must change how they vote in response to social conditions, instead of honestly voting their preference. This leaves open the question of how often this vulnerability leads to practical problems in real-world elections.

While the theorem establishes the theoretical inevitability of strategic behavior, it says nothing about when it is practically significant and to what extend strategic manipulation is possible. How frequently does strategic voting occur? What impact does it have on election outcomes? And under what conditions does theoretical manipulability become practically significant?

To investigate these issues, I have developed a modular and performant simulation framework---`kingmaker`---designed to model elections across diverse strategic environments and preference distributions. By simulating elections under different scenarios, this research provides empirical insights into the frequency, impact, and structure of strategic voting, as well as offering a deeper understanding of the robustness of various electoral systems.

In @background, I introduce the theoretical framework of social choice, outlining the foundational principles used to analyze and design elections. I define many common methods for tabulating votes, for generating ballots, and tactics for strategically voting. This section also introduces novel concepts, such as that between preferences and ballots. In @methods, I describe the design and structure of the `kingmaker` simulation framework, discussing both its implementation and the implications of its design choices for interpreting the simulation results. @results presents the outcomes of various strategic voting simulations, highlighting how different strategic behaviors influence election outcomes. Finally, in @discussion, I relate these findings to the broader context of social choice and welfare, considering what this analysis can tell us about strategic voting: when its effective, what are its limitations, and what is required to effectively vote.
